language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-22.0.1
    - android-22
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armabi-v7a-android-22
    - sys-img-x86-android-22
script: gradle assembleDebug testDebug
